
# I think we want one workflow that runs on pull requests and lints/checks/splits
# just the changed notebooks, and then we want a separate one that runs on
# pushes to master and checks all of the notebooks in the repo (but doesn't
# lint or split)

name: notebook-ci
on: 
  pull_request:
    branches: master
    paths: '**/*.ipynb'
  # push:  # XXX adding this for debugging the workflow but see above
  #   branches: master
  #   paths: '**/*.ipynb'

env:
  NB_KERNEL: python

jobs:

  process-notebooks:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install nbconvert

      - name: Get changed files
        id: changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Process notebooks
        run: python ci/process_notebooks.py ${{ steps.changes.outputs.files}}

      - name: Commit post-processed notebooks
        if: ${{ success() }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '**/*.ipynb'
          git commit -m "Generate student and TA notebooks"

      - name: Push post-processed notebooks
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
