
# I think we want one workflow that runs on pull requests and lints/checks/splits
# just the changed notebooks, and then we want a separate one that runs on
# pushes to master and checks all of the notebooks in the repo (but doesn't
# lint or split)

name: notebook-ci
on: 
  pull_request:
    branches: master
    # paths: *.ipynb  # TODO try enabling this later
  push:  # XXX adding this for debugging the workflow but see above
    branches: master

env:
  NB_KERNEL: python


jobs:

  check-notebooks:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        id: install
        run: |
          python -m pip install --upgrade pip wheel
          # XXX pip install -r requirements.txt
          # XXX pip install nbconvert treon

      - name: Get changed files
        id: changed
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
