
# I think we want one workflow that runs on pull requests and lints/checks/splits
# just the changed notebooks, and then we want a separate one that runs on
# pushes to master and checks all of the notebooks in the repo (but doesn't
# lint or split)

name: notebook-ci
on: 
  pull_request:
    branches: master
    # paths: *.ipynb  # TODO try enabling this later
  push:  # XXX adding this for debugging the workflow but see above
    branches: master

env:
  NB_KERNEL: python


jobs:

  check-notebooks:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # XXX pip install -r requirements.txt
          # XXX pip install nbconvert treon

      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.3

      - name : Print changed files
        run: cat $HOME/files.json
